# Generated by Django 4.0.4 on 2022-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelprice',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='average_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
