# Generated by Django 4.0.4 on 2022-05-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_hotelprice_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
