# Generated by Django 4.0.4 on 2022-05-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hotel_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelreview',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
