# Generated by Django 4.0.4 on 2022-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hotel_average_price_alter_hotelreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='average_price',
            field=models.CharField(max_length=500),
        ),
    ]
