# Generated by Django 4.0.4 on 2022-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_hotel_average_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprice',
            name='scrape_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
