# Generated by Django 4.0.4 on 2022-06-03 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hotelprice_scrape_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprice',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
