# Generated by Django 4.0.4 on 2022-06-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hotelprice_date_added'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotelprice',
            unique_together={('hotel', 'date_added')},
        ),
        migrations.RemoveField(
            model_name='hotelprice',
            name='scrape_date',
        ),
    ]
