# Generated by Django 4.0.4 on 2022-06-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_hotelprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('availability', models.IntegerField()),
                ('scrape_date', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
        ),
    ]
